base: 'https://www.vdi-zertifizierungen.de/'
flux_content_types: ''
flux_page_templates: ''
languages:
  -
    title: German
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: DE
    hreflang: de-DE
    direction: ltr
    flag: de
    solr_core_read: core_de
    languageId: 0
rootPageId: 10489
routes:
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?uid=10932&type=1533906435'
  -
    route: robots.txt
    type: staticText
    content: "Sitemap: https://www.vdi-zertifizierungen.de/sitemap.xml\r\nUser-agent: *\r\nDisallow: /*/Private/*\r\nDisallow: /*/Configuration/*\r\nDisallow: /typo3temp/var/*\r\nDisallow: /typo3/\r\nDisallow: *.sql\r\nDisallow: *.sql.gz\r\n"
solr_enabled_read: true
solr_host_read: '%env(EXTENSIONS_SOLR_HOST)%'
solr_path_read: '%env(EXTENSIONS_SOLR_PATH)%'
solr_port_read: '%env(EXTENSIONS_SOLR_PORT)%'
solr_scheme_read: '%env(EXTENSIONS_SOLR_SCHEME)%'
solr_use_write_connection: false
websiteTitle: ''
