base: 'https://gmbh.vdi.de/'
baseVariants:
  -
    base: 'https://gmbh-12-staging.vdi.de/'
    condition: 'getenv("ENVIRONMENT") == "STAGE"'
flux_content_types: ''
flux_page_templates: ''
languages:
  -
    title: German
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: DE
    hreflang: de-DE
    direction: ltr
    flag: de
    solr_core_read: core_de
rootPageId: 5699
solr_enabled_read: true
solr_host_read: '%env(EXTENSIONS_SOLR_HOST)%'
solr_path_read: '%env(EXTENSIONS_SOLR_PATH)%'
solr_port_read: '%env(EXTENSIONS_SOLR_PORT)%'
solr_scheme_read: '%env(EXTENSIONS_SOLR_SCHEME)%'
solr_use_write_connection: false
websiteTitle: ''
