base: 'https://www.vdi.de/en/'
baseVariants:
  -
    base: 'https://12-staging.vdi.de/en/'
    condition: 'getenv("ENVIRONMENT") == "STAGE"'
  -
    base: 'https://vdi-website-v12.ddev.site/en/'
    condition: 'getenv("ENVIRONMENT") == "DDEV"'
flux_content_types: ''
flux_page_templates: ''
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.utf8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    flag: en-us-gb
    solr_core_read: core_de
rootPageId: 3
routeEnhancers:
  GuidelineListPlugin:
    type: Extbase
    limitToPages:
      - 22
    extension: VdiGuidelines
    plugin: GuidelineList
    routes:
      -
        routePath: '/page/{page}'
        _controller: 'Guideline::list'
        _arguments:
          page: '@widget_0/currentPage'
    defaultController: 'Guideline::list'
    defaults:
      page: '0'
    requirements:
      page: \d+
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '1000'
  GuidelineDetailsPlugin:
    type: Extbase
    limitToPages:
      - 6769
    extension: VdiGuidelines
    plugin: GuidelineDetails
    routes:
      -
        routePath: '/{guideline_name}'
        _controller: 'Guideline::details'
        _arguments:
          guideline_name: guideline
    defaultController: 'Guideline::details'
    aspects:
      guideline_name:
        type: PersistedAliasMapper
        tableName: tx_vdiguidelines_domain_model_guideline
        routeFieldName: path_segment
solr_enabled_read: true
solr_host_read: '%env(EXTENSIONS_SOLR_HOST)%'
solr_path_read: '%env(EXTENSIONS_SOLR_PATH)%'
solr_port_read: '%env(EXTENSIONS_SOLR_PORT)%'
solr_scheme_read: '%env(EXTENSIONS_SOLR_SCHEME)%'
solr_use_write_connection: false
websiteTitle: ''
