<?php
return [
    'BE' => [
        'debug' => false,
        'installToolPassword' => '$argon2i$v=19$m=16384,t=16,p=2$aWE0Lzh4cVlsMVZ1MkxVOA$KMUCPH4NDOyj0dOitiE1OUYpbUxx2I3bvwZAtU0M+oo',
        'lockSSL' => true,
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
        'warning_email_addr' => 'webmaster@vdi.de',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8mb4',
                'driver' => 'mysqli',
                'tableoptions' => [
                    'charset' => 'utf8mb4',
                    'collate' => 'utf8mb4_unicode_ci',
                ],
            ],
            'NavAdb' => [
                'charset' => 'utf8mb4',
                'driver' => 'mysqli',
                'tableoptions' => [
                    'charset' => 'utf8mb4',
                    'collate' => 'utf8mb4_unicode_ci',
                ],
            ],
            'Rpro' => [
                'charset' => 'utf8mb4',
                'driver' => 'mysqli',
                'tableoptions' => [
                    'charset' => 'utf8',
                    'collate' => 'latin1_swedish_ci',
                ],
            ],
        ],
    ],
    'EXT' => [],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
            ],
        ],
        'yoast_seo' => [
            'allowedDoktypes' => [
                'blog' => 137,
            ],
        ],
    ],
    'EXTENSIONS' => [
        'aus_driver_amazon_s3' => [
            'dnsPrefetch' => '1',
            'doNotLoadAmazonLib' => '0',
            'enablePermissionsCheck' => '0',
        ],
        'backend' => [
            'backendFavicon' => '',
            'backendLogo' => 'EXT:vdi/Resources/Public/Images/Backend/logo-white.png',
            'loginBackgroundImage' => 'EXT:vdi/Resources/Public/Images/Backend/bg.png',
            'loginFootnote' => '© 2025 Verein Deutscher Ingenieure e.V.',
            'loginHighlightColor' => '#0b4395',
            'loginLogo' => 'EXT:vdi/Resources/Public/Images/Backend/logo.png',
            'loginLogoAlt' => 'VDI',
        ],
        'blog' => [
            'disablePageLayoutHeader' => '0',
            'enableGravatarProxy' => '0',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'fal_securedownload' => [
            'force_download' => '',
            'force_download_for_ext' => '',
            'login_redirect_url' => '',
            'no_access_redirect_url' => '',
            'resumable_download' => '1',
            'track_downloads' => '0',
        ],
        'femanager' => [
            'disableLog' => '0',
            'disableModule' => '0',
            'enableConfirmationModule' => '0',
            'overrideFeUserCountryFieldWithSelect' => '0',
            'setCookieOnLogin' => '0',
        ],
        'flux' => [
            'autoload' => '1',
            'compact' => '0',
            'customLayoutSelector' => '0',
            'debugMode' => '0',
            'doktypes' => '0,1,4',
            'flexFormToIrre' => '0',
            'handleErrors' => '0',
            'inheritanceMode' => 'restricted',
            'pageIntegration' => '1',
            'pagesLanguageConfigurationOverlay' => '0',
            'plugAndPlay' => '0',
            'plugAndPlayDirectory' => 'design',
            'uniqueFileFieldNames' => '0',
        ],
        'form_to_database' => [
            'csvDelimiter' => ';',
            'csvOnlyFilenameOfUploadFields' => '0',
            'hideLocationInList' => '0',
        ],
        'news' => [
            'advancedMediaPreview' => 'true',
            'archiveDate' => 'date',
            'categoryBeGroupTceFormsRestriction' => '0',
            'categoryRestriction' => '',
            'contentElementPreview' => '1',
            'contentElementRelation' => '1',
            'dateTimeNotRequired' => '0',
            'hidePageTreeForAdministrationModule' => '0',
            'manualSorting' => '0',
            'mediaPreview' => 'false',
            'prependAtCopy' => '1',
            'resourceFolderImporter' => '/news_import',
            'rteForTeaser' => '0',
            'showAdministrationModule' => '0',
            'showImporter' => '0',
            'slugBehaviour' => 'unique',
            'storageUidImporter' => '1',
            'tagPid' => '1',
        ],
        'news_administration' => [
            'hidePageTreeForAdministrationModule' => '0',
        ],
        'nnhelpers' => [
            'autoCreateFilemounts' => '1',
            'clearAllCaches' => '0',
            'deeplApiKey' => '',
            'deeplApiUrl' => 'https://api-free.deepl.com/v2/translate',
            'devModeEnabled' => '0',
            'googleGeoApiKey' => '',
            'saltingKey' => '',
            'showMod' => '1',
        ],
        'nnrestapi' => [
            'apiKeys' => 'vdi:secretpassword',
            'disableDefaultEndpoints' => '1',
            'disableDonationWarning' => '0',
            'disablePreCheck' => '1',
            'fileEncryptionKey' => '',
            'maxSessionLifetime' => '3600',
        ],
        'recaptcha' => [
            'api_server' => 'https://www.google.com/recaptcha/api.js',
            'enforceCaptcha' => '1',
            'lang' => '',
            'private_key' => '',
            'public_key' => '',
            'robotMode' => '0',
            'verify_server' => 'https://www.google.com/recaptcha/api/siteverify',
        ],
        'scheduler' => [
            'maxLifetime' => '1440',
            'showSampleTasks' => '1',
        ],
        'sf_event_mgt' => [
            'enableInvoice' => '1',
            'enableTransfer' => '1',
            'hideInlineRegistrations' => '0',
            'hideInlineRegistrationsLimit' => '500',
            'slugBehaviour' => 'unique',
        ],
        'solr' => [
            'allowSelfSignedCertificates' => '0',
            'enableRouteEnhancer' => '0',
            'includeGlobalQParameterInCacheHash' => '0',
            'monitoringType' => '1',
            'pluginNamespaces' => 'tx_solr',
            'useConfigurationFromClosestTemplate' => '0',
            'useConfigurationMonitorTables' => '',
            'useConfigurationTrackRecordsOutsideSiteroot' => '1',
        ],
        'static_info_tables' => [
            'enableManager' => '0',
        ],
        'sysfile_faker' => [
            'enable' => '1',
            'fontFile' => 'typo3conf/ext/vdi/Resources/Public/Fonts/vdi.ttf',
            'remoteHost' => 'https://www.vdi.de',
            'remoteHostBasicAuth' => '',
        ],
        'tt_address' => [
            'activatePiBase' => '0',
            'backwardsCompatFormat' => '%1$s %3$s',
            'newPagination' => '1',
            'readOnlyNameField' => '0',
            'storeBackwardsCompatName' => '0',
            'telephoneValidationPatternForJs' => '/[^\\d\\+\\s\\-]/g',
            'telephoneValidationPatternForPhp' => '/[^\\d\\+\\s\\-]/',
        ],
        'vdi' => [
            'googleApiKey' => 'AIzaSyB9o0QVBlEVrRBRMw3aemJz--4vOnpDcms',
        ],
        'vdi_events' => [
            'edudipApiToken' => '8joOs0gdWRT3lSdh1QdmwebHYndp5f27TDxEtSdBRtzQ0XKNVwDlduOteVCq',
            'edudipApiUrl' => 'https://api.edudip-next.com/',
            'edudipRecordsStorage' => '7',
            'internalEventCpIds' => '{09BFE730-EB5B-46F4-AA0E-60D7D15D3CB3},{5B25EA27-3B1D-45B7-A102-EF3AB8A3AA93}',
            'mediaFilesImportPath' => 'fileadmin/veranstaltungen/cp_va_files/',
            'onlineEventCpIds' => '{7D2D4BD3-1E86-4340-B16A-BAEC985D0EFD},{628656EE-4A95-4503-AAA7-4B9A51E1E62D}',
            'registrationExportPath' => 'fileadmin/logfiles/soap_service_cp/Anmeldungen/',
            'wfSolrUrl' => '',
            'wfUrl' => 'https://www.vdi-wissensforum.de/%1$s',
        ],
        'vdi_feuser' => [
            'useAdminApprovedRegistration' => '0',
            'useDoubleOptInAssentProcedure' => '1',
        ],
        'vdi_guidelines' => [
            'beuthUrl' => 'https://www.dinmedia.de/%1$s/langanzeige/de/%2$d.html',
            'beuthUrlWebsource' => 'vdin',
            'contentsPdfPath' => 'fileadmin/pages/vdi_de/redakteure/richtlinien/inhaltsverzeichnisse/',
            'objectionFormExcelUrl' => 'EXT:vdi_rili_einspruch/res/einspruch_einreichen/gui/einspruch_upload.php',
            'objectionFormOnlineUrl' => 'EXT:vdi_rili_einspruch/res/einspruch_einreichen/gui/einspruch_upload.php',
        ],
        'vdi_mediathek' => [
            'ffmpegBinPath' => '/usr/bin/ffmpeg',
            'ffprobeBinPath' => '/usr/bin/ffprobe',
            'searchBoxBackgroundImage' => 'EXT:vdi_mediathek/Resources/Public/Images/mediathek-visual.png',
        ],
        'vdi_online_library' => [
            'frontendUserGroupPrefix' => 'VDI-VOB',
        ],
        'vdi_optivo' => [
            'episerverAdmissionFormConfirmationMailId' => '',
            'episerverTransactionApiAuthorizationCode' => '',
            'optivoApiToken' => '',
            'optivoApiUrl' => 'https://api.broadmail.de/http/',
        ],
        'vdi_publications' => [
            'leadArchivePath' => '',
            'leadCookieExpirationInterval' => '31536000',
            'leadExportPath' => '',
            'leadTokenExpirationInterval' => '172800',
            'leadUploadPath' => '',
            'vdiFtpHost' => '',
            'vdiFtpPassword' => '',
            'vdiFtpPort' => '',
            'vdiFtpUser' => '',
        ],
        'vdi_rest_api' => [
            'ipRestrictions' => '*',
        ],
        'vdi_rili_einspruch' => [
            'rpro_live_dbaddr' => '',
            'rpro_test_dbaddr' => '',
            'select_rpro_db' => '',
        ],
        'vdi_soap_cp' => [
            'allowedIps' => '172.*.*.*',
        ],
        'vdi_verlag_sso' => [
            'accessTokenClientSecret' => '',
            'apiUrl' => '',
            'basicAuthPassword' => '',
            'basicAuthUsername' => '',
            'defaultPassword' => '',
            'loginUrl' => '',
            'newsPlusUrl' => '',
            'profileUrl' => '',
        ],
        'vhs' => [
            'disableAssetHandling' => '0',
        ],
        'webp' => [
            'convert_all' => '1',
            'converter' => 'Plan2net\\Webp\\Converter\\MagickConverter',
            'exclude_directories' => '',
            'filter_pattern' => '/\\.(jpe?g|png|gif)\\.webp$/i',
            'hide_webp' => '1',
            'mime_types' => 'image/jpeg,image/png,image/gif',
            'parameters' => 'image/jpeg::-quality 85 -define webp:lossless=false|image/png::-quality 75 -define webp:lossless=true|image/gif::-quality 85 -define webp:lossless=true',
            'silent' => '0',
            'use_system_settings' => '1',
        ],
    ],
    'FE' => [
        'cacheHash' => [
            'excludedParameters' => [
                'L',
                'pk_campaign',
                'pk_kwd',
                'utm_source',
                'utm_medium',
                'utm_campaign',
                'utm_term',
                'utm_content',
                'gclid',
                'fbclid',
                'tx_vdicareeradvice_appointmentlist[startDate][date]',
                'tx_vdicareeradvice_appointmentlist[startTime]',
                'tx_vdicareeradvice_memberappointmentlist[appointment]',
            ],
        ],
        'compressionLevel' => 9,
        'debug' => false,
        'lifetime' => 1209600,
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [
                'threads' => 4,
                'time_cost' => 5,
            ],
        ],
        'sessionDataLifetime' => 2419200,
        'sessionTimeout' => 1209600,
    ],
    'GFX' => [
        'processor' => 'ImageMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'sRGB',
        'processor_effects' => true,
        'processor_enabled' => true,
        'processor_path' => '/usr/bin/',
    ],
    'LOG' => [
        'TYPO3' => [
            'CMS' => [
                'deprecations' => [
                    'writerConfiguration' => [
                        'notice' => [
                            'TYPO3\CMS\Core\Log\Writer\FileWriter' => [
                                'disabled' => true,
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    'MAIL' => [
        'defaultMailFromAddress' => 'webmaster@vdi.de',
        'defaultMailFromName' => 'VDI e.V.',
        'defaultMailReplyToAddress' => '',
        'defaultMailReplyToName' => 'VDI e.V.',
        'transport' => 'sendmail',
        'transport_sendmail_command' => '/usr/local/bin/mailpit sendmail -t -i --smtp-addr 127.0.0.1:1025',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'caching' => [
            'cacheConfigurations' => [
                'hash' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                ],
                'imagesizes' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
                'pages' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
                'rootline' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
            ],
        ],
        'ddmmyy' => 'd.m.Y',
        'defaultScheme' => 'https',
        'devIPmask' => '',
        'displayErrors' => 0,
        'encryptionKey' => '53bf3d8f3205fd100c9ecb0c617bb5c812bd869aa1137f63a58042d63e22490a80acc68ea0c8b4f68115fd5fd1d19500',
        'exceptionalErrors' => 4096,
        'features' => [
            'security.backend.enforceContentSecurityPolicy' => true,
            'security.backend.enforceReferrer' => true,
            'unifiedPageTranslationHandling' => true,
        ],
        'phpTimeZone' => 'Europe/Berlin',
        'sitename' => 'VDI',
        'systemLocale' => 'en_US.UTF-8',
        'systemMaintainers' => [
            1,
            2,
            489,
            742,
        ],
    ],
    'scheduler' => [
        'maxLifetime' => '1440',
        'showSampleTasks' => '1',
    ],
];
