base: 'https://www.vdini-club.de'
baseVariants:
  -
    base: 'https://vdini-club-12-staging.vdi.de/'
    condition: 'getenv("ENVIRONMENT") == "STAGE"'
  -
    base: 'https://vdini-club-v12.ddev.site/'
    condition: 'getenv("ENVIRONMENT") == "DDEV"'
flux_content_types: ''
flux_page_templates: ''
languages:
  -
    title: German
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de
    direction: ltr
    flag: de
    languageId: 0
    solr_core_read: core_de
rootPageId: 5867
routes:
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?uid=6215&type=1533906435'
  -
    route: robots.txt
    type: staticText
    content: "Sitemap: https://www.vdini-club.de/sitemap.xml\nUser-agent: *\nAllow: /\nDisallow: /typo3/\nDisallow: /Hyphenopoly/\nDisallow: /typo3temp/\nDisallow: /uploads/\nDisallow: /fileadmin/\n"
solr_enabled_read: true
solr_host_read: '%env(EXTENSIONS_SOLR_HOST)%'
solr_path_read: '%env(EXTENSIONS_SOLR_PATH)%'
solr_port_read: '%env(EXTENSIONS_SOLR_PORT)%'
solr_scheme_read: '%env(EXTENSIONS_SOLR_SCHEME)%'
solr_use_write_connection: false
websiteTitle: ''
