base: 'https://positionspapiere.vdi.de/'
baseVariants:
  -
    base: 'https://positionspapiere-12-staging.vdi.de/'
    condition: 'getenv("ENVIRONMENT") == "STAGE"'
  -
    base: 'https://positionspapiere.vdi-website-v12.ddev.site/'
    condition: 'getenv("ENVIRONMENT") == "DDEV"'
flux_content_types: ''
flux_page_templates: ''
languages:
  -
    title: German
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de
    direction: ltr
    flag: de
    languageId: 0
    solr_core_read: core_de
rootPageId: 6137
solr_enabled_read: true
solr_host_read: '%env(EXTENSIONS_SOLR_HOST)%'
solr_path_read: '%env(EXTENSIONS_SOLR_PATH)%'
solr_port_read: '%env(EXTENSIONS_SOLR_PORT)%'
solr_scheme_read: '%env(EXTENSIONS_SOLR_SCHEME)%'
solr_use_write_connection: false
websiteTitle: ''
